query about {
    entry(section: [about]) {
        ... on About {
            title

            infoFrame {
                ... on InfoFrameTextFrame {
                    __typename
                    title: frameTitle
                    frameContent {
                        content
                    }
                }
                ... on InfoFrameAssetFrame {
                    __typename
                    title: frameTitle
                    label: frameLabel
                    asset: frameAsset {
                        url
                    }
                }
            }
        }
    }
}