query works($limit: Int!, $offset: Int) {
    entries: entriesConnection(section: [works], limit: $limit, offset: $offset) {
        edges {
            node {
                ... on Works {
                    title
                    uri
                    body {
                        content
                    }
                    year: workYear
                    client: workClient
                }
            }
        }
    }
}