query works($limit: Int!, $offset: Int) {
    entries: entriesConnection(section: [works], limit: $limit, offset: $offset) {
        edges {
            node {
                ... on Works {
                    title
                    slug
                    uri
                    body {
                        content
                    }
                    subtitle: workSubtitle
                    year: workYear
                    client: workClient
                    collaborators: workCollaborators {
                        name
                        url
                    }
                    links: workLinks {
                        label
                        url
                    }
                    summary: workSummary {
                        content
                    }
                }
            }
        }
    }
}