contentColumnType: text
fieldGroup: 37dec144-66f8-4a73-95c4-c9ef177c9364
handle: postalCode
instructions: ''
name: 'Postal Code'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
