contentColumnType: string
fieldGroup: 637310c2-57c6-494d-aab6-8bee7b82c1df
handle: topics
instructions: ''
name: Topics
searchable: true
settings:
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: 'Add a topic'
  source: 'group:ed81e0e2-d805-41f7-9484-b6427fdb98dd'
  sources: '*'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
