columnSuffix: zceuhrwf
contentColumnType: text
fieldGroup: 7e9c7343-1359-4b70-a3f4-dc3a1382eb60
handle: workLinks
instructions: ''
name: Links
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - Enable
            -
              - handle
              - enable
            -
              - width
              - '50'
            -
              - type
              - lightswitch
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'New window'
            -
              - handle
              - newWindow
            -
              - width
              - '50'
            -
              - type
              - lightswitch
  defaults:
    -
      __assoc__:
        -
          - col4
          - '1'
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
