columnSuffix: zdgoxkuq
contentColumnType: text
fieldGroup: 7e9c7343-1359-4b70-a3f4-dc3a1382eb60
handle: workSubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
