field: d761b95a-3218-4e96-9c97-9644fcbc56a6 # Info Frame
fieldLayouts:
  687d5a27-3a82-4ad0-a308-9dde285873da:
    tabs:
      -
        elements:
          -
            fieldUid: 709e8b92-857e-413f-98fa-01755b83e900 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aebe3a58-4de7-43e8-bd6e-95fc523f4b23 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4145d92-b496-4bba-b123-8528b0e737f6 # Asset
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  709e8b92-857e-413f-98fa-01755b83e900: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: frameTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a4145d92-b496-4bba-b123-8528b0e737f6: # Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: frameAsset
    instructions: ''
    name: Asset
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:569a8c40-8abf-44eb-ae77-3c4ae1b1830a' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:569a8c40-8abf-44eb-ae77-3c4ae1b1830a' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:d8c7a1b5-2187-413e-9ed9-e8dcb39db21a' # Files
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  aebe3a58-4de7-43e8-bd6e-95fc523f4b23: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: frameLabel
    instructions: ''
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: assetFrame
name: 'Asset Frame'
sortOrder: 2
