enableVersioning: true
handle: newsIndex
name: 'News Index'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  95e89cc5-91be-44e4-833a-5d3017e3601f:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: news
type: single
