enableVersioning: true
handle: news
name: 'News Articles'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  95e89cc5-91be-44e4-833a-5d3017e3601f:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'news/{slug}'
type: channel
