fieldLayouts:
  d0cfc9ad-0dac-4c74-a82d-274f6c331973:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 5e3f228d-3db1-4546-ab5e-389f4f36ec12 # SEO
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: General
        sortOrder: 1
handle: newsIndex
hasTitleField: true
name: 'News Index'
section: 899ea362-fe9d-45d1-94c6-288e29f7a695 # News Index
sortOrder: 1
titleFormat: '{section.name|raw}'
